# configs/datasets/btad.yaml

#####################################################################
# Datasets
#####################################################################

dataset:
  name: btad
  module: defectvad.data.btad
  class: BTADDataset

  path: null      # to be updated
  category: null  # to be updated

  img_size: 256
  crop_size: null
  normalize: true
