# configs/defaults.yaml

#####################################################################
# Datasets
#####################################################################

dataset:
  name: visa
  module: defectvad.data.visa
  class: ViSADataset

  path: null      # to be updated
  category: null  # to be updated

  img_size: 256
  crop_size: null
  normalize: true
